### ISSUE TITLE
deploy failed due to missing bucket

### ISSUE THREAD

**Issue by binchenX** [aws-samples/cdk-eks-fargate#2]
```
[0%] start: Publishing 50e10880d134a01b440991fc77d217f39f01c2d56945215ee9a3b81187c6f3b1:current
[10%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
[10%] start: Publishing c691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49c:current
[20%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
[20%] start: Publishing bafd50ae9f214e496ff8c72c6425f93dca3ccd590e20963706d5d610d9c75757:current
[30%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
[30%] start: Publishing e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68:current
[40%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
[40%] start: Publishing 844c1a4b13479b359ea0e607dccb4a04b73e22cf88cf9b64feed2c5f0de213c0:current
[50%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
[50%] start: Publishing ff8d00f9cedcafaf1ab299446ed2500b61b0b88ab40f066d05b26ff66bd58b15:current
[60%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
[60%] start: Publishing 10e0d4bba7ae4b96280b39e3351d41c9fd4487d0e005c1e18f2d50bf056b1608:current
[70%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
[70%] start: Publishing 9538b0f34da5dcc6443d0939a62235f47d615b962b7007a77b9387a3d50fc71b:current
[80%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
[80%] start: Publishing f0cbf17adc8139095eb0b4ef3c4292042f21d8c1a89620d1d0d8e8566ad0481d:current
[90%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
[90%] start: Publishing a57dd698fd3a2c2946468534f2e7d2d6094e9dc6597561ba0e17b8c4b48f6643:current
[100%] fail: No bucket named 'cdktoolkit-stagingbucket-1mdu5a7avdvjg'. Is account xxxacou bootstrapped?
x k8s-app-on-eks-fargate-stack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
at Object.publishAssets (/usr/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
at Object.deployStack (/usr/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:232:3)
at CdkToolkit.deploy (/usr/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
at initCommandLine (/usr/lib/node_modules/aws-cdk/bin/cdk.ts:209:9)
Failed to publish one or more assets. See the error messages above for more information.
```

**Comment by JasperW01** [comment]
Hi @binchenX , you need to cdk bootstrap your AWS account first. i.e. simply run "cdk bootstrap" then re-run "cdk deploy" again. 

cheers.

**Comment by binchenX** [comment]
Thanks @JasperW01 - before doing `cdk bootstrap` I also had to do this:
https://debugthis.dev/cdk/2020-07-08-aws-cdk-errors/

I think I had run cdk bootstrap before but I deleted the bucket used by cdk accidentally..
